server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-food
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create


