server:
  port: 8084

spring:
  application:
    name: order-food-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order-food
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
logging:
  file:
    path: /home/bruno/logs/orderfood.log



