spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: order-food-service
          uri: lb://order-food-service
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-food-service
                fallbackuri: forward:/orderFallBack
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallBack

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
    register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#se demorar mais de 5s pra o serviço responder, entao ativa o fallback