spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: order-food-service
          uri: lb://order-food-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
    register-with-eureka: true


