spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: order-food-service
          uri: lb://order-food-service
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-food-service
                fallbackuri: forward:/orderFallBack
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentFallBack
        - id: notification-email-service
          uri: lb://notification-email-service
          predicates:
            - Path=/emails/**
          filters:
            - name: CircuitBreaker
              args:
                name: notification-email-service
                fallbackuri: forward:/notification-emailFallback

server:
  port: 8081



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#se demorar mais de 5s pra o serviço responder, entao ativa o fallback